"use strict";

// Le Nid des Champions V1.0.2 — finition UX, données C1 manuelles et profils joueurs.
(() => {
  const safe=v=>Array.isArray(v)?v:[];
  const byId=id=>document.getElementById(id);
  const escAttr=v=>esc(String(v??""));

  function playerFormV102(form=[]){
    const map={exact:["🎯","Exact"],difference:["↔","Bon écart"],result:["✓","Bon résultat"],miss:["0","Raté"]};
    return `<div class="player-form-v102">${safe(form).slice(0,5).map(x=>{const m=map[x.result]||["·","Match"];return `<span class="player-form-${esc(x.result||"miss")}"><b>${m[0]}</b><small>${esc(m[1])}</small><em>${Number(x.points||0)} pt${Number(x.points||0)>1?"s":""}</em></span>`;}).join("")||'<div class="empty">Pas encore de résultats récents.</div>'}</div>`;
  }

  // -------------------------------------------------------------------------
  // Profil joueur — nouvelle fiche plus compacte et lisible.
  // -------------------------------------------------------------------------
  window.openPlayerQuickProfile=async function(userId){
    const p=state.profileDirectory.get(String(userId));if(!p)return toast("Joueur introuvable.","error");
    const lb=safe(state.rankingRows).find(r=>String(r.user_id)===String(userId))||{},team=typeof teamForUser==="function"?teamForUser(userId):null;
    let seasonStats=null,career=null;
    if(demoMode&&String(userId)===String(state.user?.id)){seasonStats=state.seasonProfileStats;career=state.playerCareer;}
    else if(!demoMode&&state.season){try{const [sp,cp]=await Promise.all([sb.rpc("get_player_season_profile_v090",{p_season_id:state.season.id,p_user_id:userId}),sb.rpc("get_player_career_v090",{p_user_id:userId})]);if(!sp.error)seasonStats=sp.data?.[0]||null;if(!cp.error)career=cp.data||null;}catch(_){} }
    const picks=typeof loadPublicChampionPicksV100==="function"?await loadPublicChampionPicksV100(userId):[];
    const ss=seasonStats||lb||{},cs=career?.summary||{},dist=career?.distinctions||seasonStats?.distinctions||[],mv=safe(state.nidMovementStatsV101).find(x=>String(x.user_id)===String(userId))||{};
    const points=Number(lb.points??ss.points??0),precision=Number(ss.precision_pct??lb.precision_pct??0),exact=Number(ss.exact_scores??lb.exact_scores??0),avg=Number(ss.average??lb.average??0);
    const championHtml=typeof publicChampionPicksHTMLV100==="function"?publicChampionPicksHTMLV100(picks):"";
    const root=modal(`Profil · ${p.username}`,`<div class="player-sheet-v102">
      <header class="player-hero-v102">${avatarHTML({...p,user_id:p.id||userId})}<div><span class="eyebrow gold">Joueur du Nid</span><h2>${esc(p.username)}</h2><p>${esc(p.club_heart||"Aucun club de cœur")}${team?` · ${esc(team.team_name||team.name||"")}`:""}</p></div>${String(userId)===String(state.currentRival?.rival_user_id||"")?'<span class="player-rival-v102">⚔ RIVAL</span>':""}</header>
      <section class="player-kpis-v102"><article><small>Rang</small><b>#${lb.rank||ss.rank||"—"}</b><span>meilleur #${ss.best_rank||ss.rank||"—"}</span></article><article><small>Points</small><b>${points.toFixed(0)}</b><span>${avg.toFixed(2)} / match</span></article><article><small>Exacts</small><b>${exact}</b><span>${precision.toFixed(1)}% précision</span></article><article><small>Carrière</small><b>#${cs.rank||"—"}</b><span>${Number(cs.seasons_played||0)} saison(s)</span></article></section>
      ${championHtml?`<section class="player-section-v102"><div class="player-section-title-v102"><span class="eyebrow gold">Ses champions</span><small>Choix visibles une fois verrouillés</small></div>${championHtml}</section>`:""}
      <section class="player-section-v102"><div class="player-section-title-v102"><span class="eyebrow">Le côté Nid</span><small>Casseroles, génie et séries</small></div><div class="player-fun-v102"><article class="casserole"><span>🍳</span><div><small>Casseroles</small><b>${Number(ss.casserole_points??mv.casserole_points??0)} pts</b><em>${Number(ss.casseroles??mv.casserole_events??0)} événement(s)</em></div></article><article class="genius"><span>✨</span><div><small>Génie</small><b>${Number(ss.genius_points??mv.genius_points??0)} pts</b><em>${Number(ss.genius??mv.genius_events??0)} coup(s)</em></div></article><article class="zero"><span>🥶</span><div><small>Série à zéro</small><b>${Number(mv.zero_streak||0)}</b><em>prono(s) de suite</em></div></article><article class="titles"><span>🏆</span><div><small>Palmarès</small><b>${Number(cs.titles||0)} titre(s)</b><em>${Number(cs.podiums||0)} podium(s)</em></div></article></div></section>
      <section class="player-section-v102"><div class="player-section-title-v102"><span class="eyebrow">Forme récente</span><small>Les 5 derniers pronostics scorés</small></div>${playerFormV102(ss.form||[])}</section>
      ${dist.length?`<section class="player-section-v102"><div class="player-section-title-v102"><span class="eyebrow gold">Distinctions</span></div><div class="player-dist-v102">${dist.map(d=>`<span><b>${esc(d.icon||"🏆")}</b><span><strong>${esc(d.label)}</strong><small>${esc(d.description||"")}</small></span></span>`).join("")}</div></section>`:""}
      <footer class="player-actions-v102"><button id="openPlayerMuseumBtn" class="btn secondary small" type="button">🏛️ Voir son Musée</button>${String(userId)!==String(state.user?.id)?'<button id="reactFromPlayerProfile" class="btn secondary small" type="button">😊 Réagir</button>':""}${String(userId)===String(state.currentRival?.rival_user_id||"")?'<button id="openProfileRivalCompare" class="btn secondary small" type="button">⚔ Comparer</button>':""}${state.profile?.role==="super_admin"?'<button id="superOwlFromPlayerProfile" class="btn gold small" type="button">🦉 Message du Hibou</button>':""}</footer>
    </div>`);
    root.querySelector(".modal-card")?.classList.add("player-modal-v102");
    byId("openPlayerMuseumBtn")&&(byId("openPlayerMuseumBtn").onclick=()=>openPlayerMuseum(userId));
    byId("reactFromPlayerProfile")&&(byId("reactFromPlayerProfile").onclick=()=>openPlayerReactionPicker(userId));
    byId("superOwlFromPlayerProfile")&&(byId("superOwlFromPlayerProfile").onclick=()=>openAdminOwlMessageForPlayer(userId));
    byId("openProfileRivalCompare")&&(byId("openProfileRivalCompare").onclick=openRivalQuickCompare);
  };

  // -------------------------------------------------------------------------
  // Saisie C1 manuelle : les API restent une aide, jamais un point de blocage.
  // -------------------------------------------------------------------------
  function squadToTextV102(squad){return safe(squad).map(p=>[p.name,p.position,p.nationality].filter(Boolean).join(" | ")).join("\n");}
  function textToSquadV102(text){return String(text||"").split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map((line,i)=>{const [name,position,nationality]=line.split("|").map(x=>x?.trim());return{id:-(i+1),name:name||`Joueur ${i+1}`,position:position||null,nationality:nationality||null};});}
  function clubStatRowsV102(clubId){const s=new Map(),d=new Map();safe(state.uclScorersV101).filter(x=>String(x.club_id)===String(clubId)).forEach(x=>s.set(String(x.player_external_id),x));safe(state.uclDisciplineV101).filter(x=>String(x.club_id)===String(clubId)).forEach(x=>d.set(String(x.player_external_id),x));return [...new Set([...s.keys(),...d.keys()])].map(id=>({...s.get(id),...d.get(id),player_external_id:id})).sort((a,b)=>Number(b.goals||0)-Number(a.goals||0)||String(a.player_name||"").localeCompare(String(b.player_name||""),"fr"));}

  function fillClubFormV102(root,club){if(!club)return;const set=(id,v)=>{const el=byId(id);if(el)el.value=v??"";};set("c1ShortV102",club.short_name||"");set("c1TlaV102",club.tla||"");set("c1CountryV102",club.country||"");set("c1VenueV102",club.venue||"");set("c1AddressV102",club.address||"");set("c1WebsiteV102",club.website||"");set("c1FoundedV102",club.founded||"");set("c1ColorsV102",club.club_colors||"");set("c1CoachV102",club.coach_name||"");set("c1CoachNatV102",club.coach_nationality||"");set("c1TitlesV102",club.ucl_titles||0);set("c1BestV102",club.ucl_best_result||"");set("c1HistoryV102",club.ucl_history||"");set("c1SquadV102",squadToTextV102(club.squad));renderC1PlayersV102(root,club.id);}

  function fillPlayerFormV102(row={}){const set=(id,v)=>{const el=byId(id);if(el)el.value=v??"";};set("c1PlayerIdV102",row.player_external_id||"");set("c1PlayerNameV102",row.player_name||"");set("c1PlayerPositionV102",row.position||"");set("c1PlayerNationalityV102",row.nationality||"");set("c1PlayerPlayedV102",Number(row.played_matches||0));set("c1PlayerGoalsV102",Number(row.goals||0));set("c1PlayerAssistsV102",Number(row.assists||0));set("c1PlayerPenaltiesV102",Number(row.penalties||0));set("c1PlayerYellowV102",Number(row.yellow_cards||0));set("c1PlayerYellowRedV102",Number(row.yellow_red_cards||0));set("c1PlayerRedV102",Number(row.red_cards||0));}

  function renderC1PlayersV102(root,clubId){const host=byId("c1ManualPlayersV102");if(!host)return;const rows=clubStatRowsV102(clubId);host.innerHTML=rows.length?rows.map(x=>`<div class="c1-player-admin-row-v102"><span><strong>${esc(x.player_name||"Joueur")}</strong><small>${Number(x.goals||0)} but(s) · ${Number(x.assists||0)} pd · ${Number(x.yellow_cards||0)} 🟨 · ${Number(x.red_cards||0)} 🟥</small></span><div class="actions"><button type="button" class="btn secondary small" data-c1-edit-player-v102="${escAttr(x.player_external_id)}">Modifier</button><button type="button" class="btn danger small" data-c1-delete-player-v102="${escAttr(x.player_external_id)}">×</button></div></div>`).join(""):'<div class="empty">Aucune statistique joueur enregistrée pour ce club.</div>';
    host.querySelectorAll("[data-c1-edit-player-v102]").forEach(b=>b.onclick=()=>{const row=rows.find(x=>String(x.player_external_id)===String(b.dataset.c1EditPlayerV102));fillPlayerFormV102(row||{});byId("c1PlayerNameV102")?.focus();});
    host.querySelectorAll("[data-c1-delete-player-v102]").forEach(b=>b.onclick=async()=>{if(!confirm("Supprimer ces statistiques joueur ?"))return;const {error}=await sb.rpc("admin_delete_ucl_player_v102",{p_season_id:state.season.id,p_player_external_id:Number(b.dataset.c1DeletePlayerV102)});if(error)return toast(friendlyError(error),"error");await loadUclCenterData(true);renderAdminC1ManualV102();toast("Statistiques supprimées.");});
  }

  async function renderAdminC1ManualV102(){
    const root=byId("adminC1ManualV102");if(!root)return;if(state.profile?.role!=="super_admin"){root.classList.add("hidden");return;}root.classList.remove("hidden");
    const clubs=safe(state.clubs).filter(c=>c.is_active!==false).sort((a,b)=>String(a.name).localeCompare(String(b.name),"fr"));
    const selected=state.adminC1ClubV102&&clubs.some(c=>String(c.id)===String(state.adminC1ClubV102))?state.adminC1ClubV102:clubs[0]?.id;state.adminC1ClubV102=selected;
    root.innerHTML=`<div class="section-title compact"><div><span class="eyebrow gold">Données C1 manuelles</span><h3>Clubs, palmarès, buteurs & cartons</h3><p>Football-Data remplit ce qu’il fournit. Ici tu peux compléter ou corriger le reste manuellement.</p></div><span class="chip">SUPER ADMIN</span></div>
      <div class="field"><label>Club</label><select id="c1ClubSelectV102">${clubs.map(c=>`<option value="${escAttr(c.id)}" ${String(c.id)===String(selected)?"selected":""}>${esc(c.name)}</option>`).join("")}</select></div>
      <div class="c1-manual-grid-v102"><section><h4>Fiche club</h4><div class="grid grid-3"><div class="field"><label>Nom court</label><input id="c1ShortV102"></div><div class="field"><label>Sigle</label><input id="c1TlaV102"></div><div class="field"><label>Pays</label><input id="c1CountryV102"></div><div class="field"><label>Stade</label><input id="c1VenueV102"></div><div class="field"><label>Fondé en</label><input id="c1FoundedV102" type="number"></div><div class="field"><label>Couleurs</label><input id="c1ColorsV102"></div></div><div class="field"><label>Adresse</label><input id="c1AddressV102"></div><div class="field"><label>Site</label><input id="c1WebsiteV102"></div><div class="grid grid-2"><div class="field"><label>Entraîneur</label><input id="c1CoachV102"></div><div class="field"><label>Nationalité entraîneur</label><input id="c1CoachNatV102"></div></div><div class="grid grid-2"><div class="field"><label>Ligues des champions gagnées</label><input id="c1TitlesV102" type="number" min="0"></div><div class="field"><label>Meilleur résultat / repère</label><input id="c1BestV102" placeholder="ex. Vainqueur 1993"></div></div><div class="field"><label>Historique Ligue des champions</label><textarea id="c1HistoryV102" rows="4" placeholder="Palmarès, finales, fait marquant..."></textarea></div><div class="field"><label>Effectif — une ligne par joueur : Nom | Poste | Nationalité</label><textarea id="c1SquadV102" rows="8"></textarea></div><button id="saveC1ClubV102" class="btn gold small" type="button">Enregistrer la fiche club</button></section>
      <section><h4>Buteurs & discipline</h4><input id="c1PlayerIdV102" type="hidden"><div class="field"><label>Joueur</label><input id="c1PlayerNameV102" placeholder="Nom du joueur"></div><div class="grid grid-2"><div class="field"><label>Poste</label><input id="c1PlayerPositionV102"></div><div class="field"><label>Nationalité</label><input id="c1PlayerNationalityV102"></div></div><div class="c1-player-numbers-v102"><div class="field"><label>MJ</label><input id="c1PlayerPlayedV102" type="number" min="0" value="0"></div><div class="field"><label>Buts</label><input id="c1PlayerGoalsV102" type="number" min="0" value="0"></div><div class="field"><label>Passes</label><input id="c1PlayerAssistsV102" type="number" min="0" value="0"></div><div class="field"><label>Penaltys</label><input id="c1PlayerPenaltiesV102" type="number" min="0" value="0"></div><div class="field"><label>🟨</label><input id="c1PlayerYellowV102" type="number" min="0" value="0"></div><div class="field"><label>🟨🟥</label><input id="c1PlayerYellowRedV102" type="number" min="0" value="0"></div><div class="field"><label>🟥</label><input id="c1PlayerRedV102" type="number" min="0" value="0"></div></div><div class="actions"><button id="saveC1PlayerV102" class="btn small" type="button">Enregistrer le joueur</button><button id="newC1PlayerV102" class="btn secondary small" type="button">Nouveau</button></div><div id="c1ManualPlayersV102" class="c1-player-admin-list-v102"></div></section></div><div id="c1ManualMsgV102" class="form-msg"></div>`;
    const club=clubs.find(c=>String(c.id)===String(selected));fillClubFormV102(root,club);
    byId("c1ClubSelectV102").onchange=e=>{state.adminC1ClubV102=e.target.value;renderAdminC1ManualV102();};
    byId("newC1PlayerV102").onclick=()=>fillPlayerFormV102({});
    byId("saveC1ClubV102").onclick=async()=>{const id=byId("c1ClubSelectV102").value;const args={p_club_id:id,p_short_name:byId("c1ShortV102").value,p_tla:byId("c1TlaV102").value,p_country:byId("c1CountryV102").value,p_venue:byId("c1VenueV102").value,p_address:byId("c1AddressV102").value,p_website:byId("c1WebsiteV102").value,p_founded:Number(byId("c1FoundedV102").value)||null,p_club_colors:byId("c1ColorsV102").value,p_coach_name:byId("c1CoachV102").value,p_coach_nationality:byId("c1CoachNatV102").value,p_squad:textToSquadV102(byId("c1SquadV102").value),p_ucl_titles:Number(byId("c1TitlesV102").value)||0,p_ucl_best_result:byId("c1BestV102").value,p_ucl_history:byId("c1HistoryV102").value};const {error}=await sb.rpc("admin_save_club_c1_v102",args);if(error)return setMsg("#c1ManualMsgV102",friendlyError(error),"error");const {data}=await sb.from("clubs").select("*").eq("id",id).single();if(data){const i=state.clubs.findIndex(c=>String(c.id)===String(id));if(i>=0)state.clubs[i]={...state.clubs[i],...data};}setMsg("#c1ManualMsgV102","Fiche club enregistrée.","ok");renderUclCenter?.();};
    byId("saveC1PlayerV102").onclick=async()=>{const n=byId("c1PlayerNameV102").value.trim();if(!n)return setMsg("#c1ManualMsgV102","Nom du joueur obligatoire.","error");const val=id=>Math.max(0,Number(byId(id).value)||0);const idRaw=byId("c1PlayerIdV102").value;const {error}=await sb.rpc("admin_upsert_ucl_player_v102",{p_season_id:state.season.id,p_club_id:byId("c1ClubSelectV102").value,p_player_name:n,p_position:byId("c1PlayerPositionV102").value,p_nationality:byId("c1PlayerNationalityV102").value,p_played_matches:val("c1PlayerPlayedV102"),p_goals:val("c1PlayerGoalsV102"),p_assists:val("c1PlayerAssistsV102"),p_penalties:val("c1PlayerPenaltiesV102"),p_yellow_cards:val("c1PlayerYellowV102"),p_yellow_red_cards:val("c1PlayerYellowRedV102"),p_red_cards:val("c1PlayerRedV102"),p_player_external_id:idRaw?Number(idRaw):null});if(error)return setMsg("#c1ManualMsgV102",friendlyError(error),"error");await loadUclCenterData(true);fillPlayerFormV102({});renderAdminC1ManualV102();renderUclCenter?.();toast("Statistiques C1 enregistrées.");};
  }
  window.renderAdminC1ManualV102=renderAdminC1ManualV102;

  const baseRenderAdminV102=window.renderAdmin;
  if(typeof baseRenderAdminV102==="function")window.renderAdmin=function(){const r=baseRenderAdminV102.apply(this,arguments);renderAdminC1ManualV102();return r;};

  window.renderRelease102=function(){if(["admin","super_admin"].includes(state.profile?.role))renderAdminC1ManualV102();};
})();
