window.NIDC_CONFIG = {
  SUPABASE_URL: "https://YOUR_PROJECT.supabase.co",
  SUPABASE_ANON_KEY: "YOUR_SUPABASE_ANON_KEY",
  APP_VERSION: "0.6.2",
  DEFAULT_SEASON_SLUG: "ucl-2026-27",
  ODDS_EXTERNAL_ENABLED: false,
  DEMO_WHEN_UNCONFIGURED: true
};
