import fs from 'node:fs';
import assert from 'node:assert/strict';
const app=fs.readFileSync(new URL('../assets/js/app.js', import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../index.html', import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../assets/css/app.css', import.meta.url),'utf8');
const sw=fs.readFileSync(new URL('../sw.js', import.meta.url),'utf8');
const version=fs.readFileSync(new URL('../VERSION', import.meta.url),'utf8').trim();
const config=fs.readFileSync(new URL('../config.example.js', import.meta.url),'utf8');
const checklist=fs.readFileSync(new URL('../docs/TEST_CHECKLIST_V0.4.2.md', import.meta.url),'utf8');
assert.equal(version,'0.4.2');
assert.match(sw,/nid-champions-v0\.4\.2/);
assert.match(config,/APP_VERSION: \"0\.4\.2\"/);
assert.match(checklist,/AS Monaco affiche \*\*France 🇫🇷\*\*/);
assert.match(html,/V0\.4\.2/);
assert.match(app,/function clubCountry\(club\)/);
assert.match(app,/identity\.includes\("monaco"\)/);
assert.match(app,/return \{name:"France",flag:"🇫🇷"\}/);
assert.match(app,/function clubCountryHTML\(club\)/);
assert.match(app,/class="club-country"/);
assert.match(app,/clubCountryHTML\(m\.home_club\)/);
assert.match(app,/clubCountryHTML\(m\.away_club\)/);
assert.match(app,/clubCountryHTML\(next\.home_club\)/);
assert.match(app,/clubCountryHTML\(next\.away_club\)/);
assert.match(css,/V0\.4\.2 — Pays des clubs/);
assert.match(css,/\.club-country/);
// Non-régression UX V0.4.1 et moteur V0.4.0
assert.match(html,/class="sidebar"/);
assert.match(html,/id="championFirstCard"/);
assert.match(app,/save_champion_pick_v040/);
assert.match(app,/admin_set_knockout_match_state_v040/);
console.log('V0.4.2 release tests: OK');
