import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(__dirname,"..");
const read=rel=>fs.readFileSync(path.join(root,rel),"utf8");
let pass=0,fail=0;
const check=(name,ok)=>{if(ok){pass++;console.log("PASS",name);}else{fail++;console.error("FAIL",name);}};
const index=read("index.html"),app=read("js/app.js"),r101=read("js/release101.js"),r102c=read("js/release102c.js"),r102d=read("js/release102d.js"),edge=read("supabase/functions/sync-football-data/index.ts"),sw=read("sw.js"),sql=read("sql/HOTFIX_V1.0.2d_DEDUP_UCL_PLAYERS.sql");
check("index.js",index.includes('js/release102d.js'));
check("index.css",index.includes('css/release102d.css'));
check("app.hook",app.includes('renderRelease102d()'));
check("renderer.scorers",r101.includes('uclDedupeRowsV102d(state.uclScorersV101'));
check("renderer.cards",r101.includes('disciplineRowsV102d().filter'));
check("renderer.single-card",r101.includes('ucl-discipline-row-v102d')&&!r101.includes('${Number(x.yellow_red_cards||0)} 🟨🟥 · ${Number(x.red_cards||0)} 🟥</small>'));
check("102c.detail-removed",r102c.includes('if(detail) detail.remove()'));
check("runtime.dedupe",r102d.includes('function dedupeRowsV102d'));
check("sync.scorers",edge.includes('uniqueScorersV102d'));
check("sync.cards",edge.includes('uniqueDisciplineV102d'));
check("sql.all-duplicates",sql.includes('having count(*) > 1')&&!sql.includes('count(distinct club_id) <= 1'));
check("version",read("VERSION").trim()==="1.0.2d");
check("cache",sw.includes('v1.0.2d-ucl-dedupe'));
console.log(`\n${pass} PASS · ${fail} FAIL`);
process.exit(fail?1:0);
