import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,"..");
const checks=[];
const test=(name,ok)=>checks.push([name,Boolean(ok)]);
const js=fs.readFileSync(path.join(root,"js/release102a.js"),"utf8");
const css=fs.readFileSync(path.join(root,"css/release102a.css"),"utf8");
const sql=fs.readFileSync(path.join(root,"sql/HOTFIX_V1.0.2a_EXISTING_DB.sql"),"utf8");
test("Classement sans max-height",css.includes("max-height:none!important"));
test("Matchs sans couleurs Team",css.includes("AUCUNE couleur Team"));
test("Team par joueur",js.includes("teamForUser(userId)"));
test("Détails match/prono/résultat",js.includes("Prono")&&js.includes("Résultat"));
test("RPC détails événements",sql.includes("get_gamification_event_details_v102a"));
test("app_settings sans description",!sql.includes("key,value,description"));
for(const [n,ok] of checks)console.log(`${ok?"PASS":"FAIL"} - ${n}`);
if(checks.some(x=>!x[1]))process.exit(1);
console.log(`${checks.length} PASS · 0 FAIL`);
