import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
let pass=0,fail=0;
const test=(name,ok)=>{console.log(`${ok?"PASS":"FAIL"} ${name}`);ok?pass++:fail++;};
const read=rel=>fs.readFileSync(path.join(root,rel),"utf8");
const html=read("index.html"),app=read("js/app.js"),rel=read("js/release102c.js"),sw=read("sw.js"),edge=read("supabase/functions/sync-football-data/index.ts"),sql=read("sql/HOTFIX_V1.0.2c_PLAYER_STATS.sql");
test("release102c chargée",html.includes('js/release102c.js'));
test("release102c après release102",html.indexOf('js/release102c.js')>html.indexOf('js/release102.js'));
test("hook global 102c",app.includes('renderRelease102c()'));
test("dédoublonnage buteurs/cartons",rel.includes('dedupeRowsV102c')&&rel.includes('Math.max'));
test("rouge prioritaire à l'affichage",rel.includes('if(r>0) primary=`${r} 🟥`'));
test("cache PWA 102c",sw.includes('v1.0.2c-player-stats')&&sw.includes('./js/release102c.js'));
test("Football-Data RED_CARD",edge.includes('"RED_CARD"'));
test("Football-Data YELLOW_CARD",edge.includes('"YELLOW_CARD"'));
test("Football-Data SECOND_YELLOW_CARD",edge.includes('"SECOND_YELLOW_CARD"'));
test("SQL dédoublonne sans sommer",sql.includes('max(s.goals)')&&sql.includes('max(s.red_cards)'));
test("SQL récupère les clubs",sql.includes('with club_map as'));
test("version SQL 1.0.2c",sql.includes('1.0.2c'));
console.log(`\n${pass} PASS · ${fail} FAIL`);if(fail)process.exit(1);
