import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const read=p=>fs.readFileSync(path.join(root,p),"utf8");
let pass=0,fail=0;const check=(name,ok,detail="")=>{console.log(`${ok?"PASS":"FAIL"} ${name}${detail?` — ${detail}`:""}`);ok?pass++:fail++;};
const index=read("index.html"),rel=read("js/release100.js"),notif=read("js/notifications.js"),profile=read("js/profile.js"),edge=read("supabase/functions/push-dispatch/index.ts"),sql=read("sql/HOTFIX_V1.0.0_EXISTING_DB.sql"),sw=read("sw.js");
check("version.file",read("VERSION").trim()==="1.0.0");
check("version.config",read("config.js").includes('APP_VERSION: "1.0.0"'));
check("version.cache",sw.includes("nid-champions-v1.0.0-live-ux"));
check("release.wired",index.includes("css/release100.css")&&index.includes("js/release100.js"));
check("release.cached",sw.includes("release100.css")&&sw.includes("release100.js"));
check("home.no-champion-card",!index.includes('id="homeChampionSummary"')&&!index.includes("La grande intuition"));
check("home.live-carousel",rel.includes("Les matchs en direct")&&rel.includes("showMatchPredictions"));
check("home.movement",rel.includes("Le patron du Nid")&&rel.includes("Casserole du Nid")&&rel.includes("Record du Nid"));
check("ranking.cards",index.includes('class="ranking-list-v100"')&&rel.includes("ranking-row-v100"));
check("predictions.finished-bottom",rel.includes("finished-separator-v100")&&rel.includes("statusWeight"));
check("admin.no-new-matchday",!index.includes('id="createMatchdayBtn"')&&!index.includes('id="adminMdNumber"'));
check("admin.grouped-matchdays",rel.includes("admin-matchday-group-v100")&&rel.includes("matchdaySortV100"));
check("profile.other-champions",profile.includes("loadPublicChampionPicksV100")&&profile.includes("Ses champions"));
check("push.player-rpc",notif.includes("register_my_push_subscription_v100")&&sql.includes("register_my_push_subscription_v100"));
check("push.preferences-enabled",notif.includes("push_enabled:true")&&sql.includes("push_enabled=true"));
check("ranking.notifications-deferred",edge.includes("deferred:true")&&edge.includes('.eq("status","live")'));
check("ranking.notifications-dedup",edge.includes("const sourceKey=`rank-change:${season.id}")&&sql.includes("duplicate_rank_notifications"));
check("museum.records-active",sql.includes("if finished_matches=0 then return")&&!sql.includes("finished_matches<>total_matches"));
check("sql.version",sql.includes('\'app_version\',\'"1.0.0"\'::jsonb'));
console.log(`\nRésumé V1.0.0: ${pass} PASS · ${fail} FAIL`);process.exitCode=fail?1:0;
