import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,"..");
const read=p=>fs.readFileSync(path.join(root,p),"utf8");
const exists=p=>fs.existsSync(path.join(root,p));
const checks=[];
const ok=(name,cond)=>checks.push([name,!!cond]);
const index=read("index.html"),r102=read("js/release102.js"),r101=read("js/release101.js"),css=read("css/release102.css"),avatars=read("js/avatars.js"),data=read("js/data.js"),sql=read("sql/HOTFIX_V1.0.2_EXISTING_DB.sql"),sw=read("sw.js");
ok("version 1.0.2",read("VERSION").trim()==="1.0.2");
ok("release102 JS chargé",index.includes('js/release102.js'));
ok("release102 CSS chargée",index.includes('css/release102.css'));
ok("formulaire ajout match caché",css.includes('admin-panel[data-admin-panel="matches"]>.admin-builder-v100'));
ok("classement fond neutre",css.includes('#view-ranking .ranking-row-v100'));
ok("sticky desktop supprimé",css.includes('@media(min-width:761px){#view-ranking .my-ranking-sticky{display:none!important}}'));
ok("profil joueur v102",r102.includes('player-sheet-v102'));
ok("admin C1 manuel",r102.includes('adminC1ManualV102')&&index.includes('adminC1ManualV102'));
ok("RPC club manuel",sql.includes('admin_save_club_c1_v102'));
ok("RPC stats joueur",sql.includes('admin_upsert_ucl_player_v102'));
ok("palmarès club",sql.includes('ucl_titles')&&r101.includes('club.ucl_titles'));
ok("historique C1",data.includes('ucl_history')&&r101.includes('club.ucl_history'));
ok("étoile brodée",avatars.includes('world-cup-winner-star-2026.png')&&exists('assets/ui/world-cup-winner-star-2026.png'));
ok("star mise en cache",sw.includes('world-cup-winner-star-2026.png'));
ok("release102 mise en cache",sw.includes('release102.js')&&sw.includes('release102.css'));
let fails=0;for(const [name,pass] of checks){console.log(`${pass?'PASS':'FAIL'} ${name}`);if(!pass)fails++;}console.log(`\n${checks.length-fails} PASS · ${fails} FAIL`);process.exitCode=fails?1:0;
