-- LE NID DES CHAMPIONS — NETTOYAGE AVATARS V0.9.9
-- Supprime les 90 anciens avatars placeholder et conserve uniquement les 168 nouveaux avatars illustrés.
-- À exécuter UNE FOIS sur une base existante après déploiement du frontend.

begin;

alter table public.profiles alter column avatar_key set default 'avatar-hibou-humour-personnages-chanceux';

-- Les joueurs qui utilisaient une ancienne clé reviennent sur un avatar neutre réellement présent.
update public.profiles
set avatar_key = 'avatar-hibou-humour-personnages-chanceux',
    avatar_updated_at = now()
where avatar_source = 'library'
  and (avatar_key in (
    'avatar-hibou-royal',
    'avatar-hibou-argent',
    'avatar-hibou-or',
    'avatar-hibou-saphir',
    'avatar-hibou-amethyste',
    'avatar-hibou-velours',
    'avatar-hibou-couronne',
    'avatar-hibou-imperial',
    'avatar-hibou-europe',
    'avatar-hibou-prestige',
    'avatar-hibou-minuit',
    'avatar-hibou-eclipse',
    'avatar-hibou-lunaire',
    'avatar-hibou-nebuleuse',
    'avatar-hibou-astral',
    'avatar-hibou-constellation',
    'avatar-hibou-etoile',
    'avatar-hibou-comete',
    'avatar-hibou-orbite',
    'avatar-hibou-galaxie',
    'avatar-hibou-echarpe',
    'avatar-hibou-tambour',
    'avatar-hibou-tribune',
    'avatar-hibou-ultra',
    'avatar-hibou-drapeau',
    'avatar-hibou-chant',
    'avatar-hibou-stade',
    'avatar-hibou-kop',
    'avatar-hibou-tifo',
    'avatar-hibou-fumigene',
    'avatar-hibou-buteur',
    'avatar-hibou-gardien',
    'avatar-hibou-coach',
    'avatar-hibou-arbitre',
    'avatar-hibou-capitaine',
    'avatar-hibou-meneur',
    'avatar-hibou-defenseur',
    'avatar-hibou-ailier',
    'avatar-hibou-numero10',
    'avatar-hibou-remplacant',
    'avatar-hibou-coupe',
    'avatar-hibou-medaille',
    'avatar-hibou-champion',
    'avatar-hibou-finale',
    'avatar-hibou-podium',
    'avatar-hibou-victoire',
    'avatar-hibou-etoile-or',
    'avatar-hibou-trophee',
    'avatar-hibou-legende',
    'avatar-hibou-dynastie',
    'avatar-hibou-casserole',
    'avatar-hibou-poele',
    'avatar-hibou-boulet',
    'avatar-hibou-perdu',
    'avatar-hibou-endormi',
    'avatar-hibou-retard',
    'avatar-hibou-var',
    'avatar-hibou-carton',
    'avatar-hibou-zero',
    'avatar-hibou-mauvaise-foi',
    'avatar-hibou-masque',
    'avatar-hibou-ombre',
    'avatar-hibou-fantome',
    'avatar-hibou-secret',
    'avatar-hibou-oracle',
    'avatar-hibou-prophete',
    'avatar-hibou-mage',
    'avatar-hibou-alchimiste',
    'avatar-hibou-sorcier',
    'avatar-hibou-enigme',
    'avatar-hibou-neon',
    'avatar-hibou-cyber',
    'avatar-hibou-hologramme',
    'avatar-hibou-quantique',
    'avatar-hibou-electrique',
    'avatar-hibou-plasma',
    'avatar-hibou-vector',
    'avatar-hibou-digital',
    'avatar-hibou-android',
    'avatar-hibou-cosmos',
    'avatar-hibou-cristal',
    'avatar-hibou-diamant',
    'avatar-hibou-obsidienne',
    'avatar-hibou-rubis',
    'avatar-hibou-emeraude',
    'avatar-hibou-opale',
    'avatar-hibou-titane',
    'avatar-hibou-platine',
    'avatar-hibou-arcane',
    'avatar-hibou-aurora'
  ) or avatar_key in ('owl-gold','owl-blue','owl-violet') or avatar_key is null or btrim(avatar_key)='');

-- Retrait définitif des 90 anciens choix du catalogue Supabase.
delete from public.player_avatar_catalog
where avatar_key in (
    'avatar-hibou-royal',
    'avatar-hibou-argent',
    'avatar-hibou-or',
    'avatar-hibou-saphir',
    'avatar-hibou-amethyste',
    'avatar-hibou-velours',
    'avatar-hibou-couronne',
    'avatar-hibou-imperial',
    'avatar-hibou-europe',
    'avatar-hibou-prestige',
    'avatar-hibou-minuit',
    'avatar-hibou-eclipse',
    'avatar-hibou-lunaire',
    'avatar-hibou-nebuleuse',
    'avatar-hibou-astral',
    'avatar-hibou-constellation',
    'avatar-hibou-etoile',
    'avatar-hibou-comete',
    'avatar-hibou-orbite',
    'avatar-hibou-galaxie',
    'avatar-hibou-echarpe',
    'avatar-hibou-tambour',
    'avatar-hibou-tribune',
    'avatar-hibou-ultra',
    'avatar-hibou-drapeau',
    'avatar-hibou-chant',
    'avatar-hibou-stade',
    'avatar-hibou-kop',
    'avatar-hibou-tifo',
    'avatar-hibou-fumigene',
    'avatar-hibou-buteur',
    'avatar-hibou-gardien',
    'avatar-hibou-coach',
    'avatar-hibou-arbitre',
    'avatar-hibou-capitaine',
    'avatar-hibou-meneur',
    'avatar-hibou-defenseur',
    'avatar-hibou-ailier',
    'avatar-hibou-numero10',
    'avatar-hibou-remplacant',
    'avatar-hibou-coupe',
    'avatar-hibou-medaille',
    'avatar-hibou-champion',
    'avatar-hibou-finale',
    'avatar-hibou-podium',
    'avatar-hibou-victoire',
    'avatar-hibou-etoile-or',
    'avatar-hibou-trophee',
    'avatar-hibou-legende',
    'avatar-hibou-dynastie',
    'avatar-hibou-casserole',
    'avatar-hibou-poele',
    'avatar-hibou-boulet',
    'avatar-hibou-perdu',
    'avatar-hibou-endormi',
    'avatar-hibou-retard',
    'avatar-hibou-var',
    'avatar-hibou-carton',
    'avatar-hibou-zero',
    'avatar-hibou-mauvaise-foi',
    'avatar-hibou-masque',
    'avatar-hibou-ombre',
    'avatar-hibou-fantome',
    'avatar-hibou-secret',
    'avatar-hibou-oracle',
    'avatar-hibou-prophete',
    'avatar-hibou-mage',
    'avatar-hibou-alchimiste',
    'avatar-hibou-sorcier',
    'avatar-hibou-enigme',
    'avatar-hibou-neon',
    'avatar-hibou-cyber',
    'avatar-hibou-hologramme',
    'avatar-hibou-quantique',
    'avatar-hibou-electrique',
    'avatar-hibou-plasma',
    'avatar-hibou-vector',
    'avatar-hibou-digital',
    'avatar-hibou-android',
    'avatar-hibou-cosmos',
    'avatar-hibou-cristal',
    'avatar-hibou-diamant',
    'avatar-hibou-obsidienne',
    'avatar-hibou-rubis',
    'avatar-hibou-emeraude',
    'avatar-hibou-opale',
    'avatar-hibou-titane',
    'avatar-hibou-platine',
    'avatar-hibou-arcane',
    'avatar-hibou-aurora'
  );

-- Bibliothèque officielle actuelle : 168 avatars.
insert into public.player_avatar_catalog(avatar_key,label,category,sort_order,asset_path,active)
values
  ('avatar-hibou-club-psg','Paris Saint-Germain','Clubs · Ligue 1',1,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-psg.png',true),
  ('avatar-hibou-club-om','Olympique de Marseille','Clubs · Ligue 1',2,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-om.png',true),
  ('avatar-hibou-club-ol','Olympique Lyonnais','Clubs · Ligue 1',3,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-ol.png',true),
  ('avatar-hibou-club-monaco','AS Monaco','Clubs · Ligue 1',4,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-monaco.png',true),
  ('avatar-hibou-club-lille','LOSC Lille','Clubs · Ligue 1',5,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-lille.png',true),
  ('avatar-hibou-club-nice','OGC Nice','Clubs · Ligue 1',6,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-nice.png',true),
  ('avatar-hibou-club-lens','RC Lens','Clubs · Ligue 1',7,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-lens.png',true),
  ('avatar-hibou-club-rennes','Stade Rennais','Clubs · Ligue 1',8,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-rennes.png',true),
  ('avatar-hibou-club-nantes','FC Nantes','Clubs · Ligue 1',9,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-nantes.png',true),
  ('avatar-hibou-club-brest','Stade Brestois 29','Clubs · Ligue 1',10,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-brest.png',true),
  ('avatar-hibou-club-strasbourg','RC Strasbourg','Clubs · Ligue 1',11,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-strasbourg.png',true),
  ('avatar-hibou-club-toulouse','Toulouse FC','Clubs · Ligue 1',12,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-toulouse.png',true),
  ('avatar-hibou-club-auxerre','AJ Auxerre','Clubs · Ligue 1',13,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-auxerre.png',true),
  ('avatar-hibou-club-reims','Stade de Reims','Clubs · Ligue 1',14,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-reims.png',true),
  ('avatar-hibou-club-le-havre','Le Havre AC','Clubs · Ligue 1',15,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-le-havre.png',true),
  ('avatar-hibou-club-montpellier','Montpellier HSC','Clubs · Ligue 1',16,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-montpellier.png',true),
  ('avatar-hibou-club-saint-etienne','AS Saint-Étienne','Clubs · Ligue 1',17,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-saint-etienne.png',true),
  ('avatar-hibou-club-angers','Angers SCO','Clubs · Ligue 1',18,'assets/avatars/nid/clubs/ligue-1/avatar-hibou-club-angers.png',true),
  ('avatar-hibou-club-real-madrid','Real Madrid','Clubs · Europe',19,'assets/avatars/nid/clubs/europe/avatar-hibou-club-real-madrid.png',true),
  ('avatar-hibou-club-barcelone','FC Barcelone','Clubs · Europe',20,'assets/avatars/nid/clubs/europe/avatar-hibou-club-barcelone.png',true),
  ('avatar-hibou-club-atletico-madrid','Atlético de Madrid','Clubs · Europe',21,'assets/avatars/nid/clubs/europe/avatar-hibou-club-atletico-madrid.png',true),
  ('avatar-hibou-club-arsenal','Arsenal','Clubs · Europe',22,'assets/avatars/nid/clubs/europe/avatar-hibou-club-arsenal.png',true),
  ('avatar-hibou-club-liverpool','Liverpool','Clubs · Europe',23,'assets/avatars/nid/clubs/europe/avatar-hibou-club-liverpool.png',true),
  ('avatar-hibou-club-manchester-city','Manchester City','Clubs · Europe',24,'assets/avatars/nid/clubs/europe/avatar-hibou-club-manchester-city.png',true),
  ('avatar-hibou-club-manchester-united','Manchester United','Clubs · Europe',25,'assets/avatars/nid/clubs/europe/avatar-hibou-club-manchester-united.png',true),
  ('avatar-hibou-club-chelsea','Chelsea','Clubs · Europe',26,'assets/avatars/nid/clubs/europe/avatar-hibou-club-chelsea.png',true),
  ('avatar-hibou-club-bayern-munich','Bayern Munich','Clubs · Europe',27,'assets/avatars/nid/clubs/europe/avatar-hibou-club-bayern-munich.png',true),
  ('avatar-hibou-club-juventus','Juventus','Clubs · Europe',28,'assets/avatars/nid/clubs/europe/avatar-hibou-club-juventus.png',true),
  ('avatar-hibou-club-ac-milan','AC Milan','Clubs · Europe',29,'assets/avatars/nid/clubs/europe/avatar-hibou-club-ac-milan.png',true),
  ('avatar-hibou-club-inter-milan','Inter Milan','Clubs · Europe',30,'assets/avatars/nid/clubs/europe/avatar-hibou-club-inter-milan.png',true),
  ('avatar-hibou-club-naples','SSC Napoli','Clubs · Europe',31,'assets/avatars/nid/clubs/europe/avatar-hibou-club-naples.png',true),
  ('avatar-hibou-club-dortmund','Borussia Dortmund','Clubs · Europe',32,'assets/avatars/nid/clubs/europe/avatar-hibou-club-dortmund.png',true),
  ('avatar-hibou-club-ajax','Ajax Amsterdam','Clubs · Europe',33,'assets/avatars/nid/clubs/europe/avatar-hibou-club-ajax.png',true),
  ('avatar-hibou-club-benfica','Benfica','Clubs · Europe',34,'assets/avatars/nid/clubs/europe/avatar-hibou-club-benfica.png',true),
  ('avatar-hibou-club-porto','FC Porto','Clubs · Europe',35,'assets/avatars/nid/clubs/europe/avatar-hibou-club-porto.png',true),
  ('avatar-hibou-club-celtic','Celtic Glasgow','Clubs · Europe',36,'assets/avatars/nid/clubs/europe/avatar-hibou-club-celtic.png',true),
  ('avatar-hibou-brest-drapeau','Brest · Drapeau rouge et blanc','Stade Brestois · Spécial',37,'assets/avatars/nid/clubs/stade-brestois/avatar-hibou-brest-drapeau.png',true),
  ('avatar-hibou-brest-biere','Brest · Bière au port','Stade Brestois · Spécial',38,'assets/avatars/nid/clubs/stade-brestois/avatar-hibou-brest-biere.png',true),
  ('avatar-hibou-brest-fumigene','Brest · Fumigène breton','Stade Brestois · Spécial',39,'assets/avatars/nid/clubs/stade-brestois/avatar-hibou-brest-fumigene.png',true),
  ('avatar-hibou-brest-capitaine','Brest · Capitaine du port','Stade Brestois · Spécial',40,'assets/avatars/nid/clubs/stade-brestois/avatar-hibou-brest-capitaine.png',true),
  ('avatar-hibou-brest-phare','Brest · Gardien du phare','Stade Brestois · Spécial',41,'assets/avatars/nid/clubs/stade-brestois/avatar-hibou-brest-phare.png',true),
  ('avatar-hibou-brest-pluie','Brest · Jour de pluie','Stade Brestois · Spécial',42,'assets/avatars/nid/clubs/stade-brestois/avatar-hibou-brest-pluie.png',true),
  ('avatar-hibou-brest-tambour','Brest · Tambour du kop','Stade Brestois · Spécial',43,'assets/avatars/nid/clubs/stade-brestois/avatar-hibou-brest-tambour.png',true),
  ('avatar-hibou-brest-canape','Brest · Match au canapé','Stade Brestois · Spécial',44,'assets/avatars/nid/clubs/stade-brestois/avatar-hibou-brest-canape.png',true),
  ('avatar-hibou-brest-triskell','Brest · Triskell porte-bonheur','Stade Brestois · Spécial',45,'assets/avatars/nid/clubs/stade-brestois/avatar-hibou-brest-triskell.png',true),
  ('avatar-hibou-brest-emotion','Brest · Ému aux larmes','Stade Brestois · Spécial',46,'assets/avatars/nid/clubs/stade-brestois/avatar-hibou-brest-emotion.png',true),
  ('avatar-hibou-brest-ultra','Brest · Ultra au fumigène','Stade Brestois · Spécial',47,'assets/avatars/nid/clubs/stade-brestois/avatar-hibou-brest-ultra.png',true),
  ('avatar-hibou-brest-super-hibou','Brest · Super Hibou','Stade Brestois · Spécial',48,'assets/avatars/nid/clubs/stade-brestois/avatar-hibou-brest-super-hibou.png',true),
  ('avatar-hibou-humour-apero-biere','Bière du Hibou','Humour · Apéro',49,'assets/avatars/nid/humour/apero/avatar-hibou-humour-apero-biere.png',true),
  ('avatar-hibou-humour-apero-bouteille-vip','Bouteille VIP','Humour · Apéro',50,'assets/avatars/nid/humour/apero/avatar-hibou-humour-apero-bouteille-vip.png',true),
  ('avatar-hibou-humour-apero-decapsuleur','Décapsuleur officiel','Humour · Apéro',51,'assets/avatars/nid/humour/apero/avatar-hibou-humour-apero-decapsuleur.png',true),
  ('avatar-hibou-humour-apero-lendemain-match','Lendemain de match','Humour · Apéro',52,'assets/avatars/nid/humour/apero/avatar-hibou-humour-apero-lendemain-match.png',true),
  ('avatar-hibou-humour-apero-tournee-generale','Tournée générale','Humour · Apéro',53,'assets/avatars/nid/humour/apero/avatar-hibou-humour-apero-tournee-generale.png',true),
  ('avatar-hibou-humour-apero-bretzel-kop','Bretzel du kop','Humour · Apéro',54,'assets/avatars/nid/humour/apero/avatar-hibou-humour-apero-bretzel-kop.png',true),
  ('avatar-hibou-humour-apero-apero-transat','Apéro transat','Humour · Apéro',55,'assets/avatars/nid/humour/apero/avatar-hibou-humour-apero-apero-transat.png',true),
  ('avatar-hibou-humour-apero-dj-nid','DJ du Nid','Humour · Apéro',56,'assets/avatars/nid/humour/apero/avatar-hibou-humour-apero-dj-nid.png',true),
  ('avatar-hibou-humour-apero-porte-voix-mousse','Porte-voix et mousse','Humour · Apéro',57,'assets/avatars/nid/humour/apero/avatar-hibou-humour-apero-porte-voix-mousse.png',true),
  ('avatar-hibou-humour-apero-barman','Barman du Nid','Humour · Apéro',58,'assets/avatars/nid/humour/apero/avatar-hibou-humour-apero-barman.png',true),
  ('avatar-hibou-humour-apero-cacahuetes-pression','Cacahuètes & pression','Humour · Apéro',59,'assets/avatars/nid/humour/apero/avatar-hibou-humour-apero-cacahuetes-pression.png',true),
  ('avatar-hibou-humour-apero-haut-de-biere','Chapeau haut-de-bière','Humour · Apéro',60,'assets/avatars/nid/humour/apero/avatar-hibou-humour-apero-haut-de-biere.png',true),
  ('avatar-hibou-humour-tribune-tambour-kop','Tambour du kop','Humour · Tribune',61,'assets/avatars/nid/humour/tribune/avatar-hibou-humour-tribune-tambour-kop.png',true),
  ('avatar-hibou-humour-tribune-megaphone','Mégaphone','Humour · Tribune',62,'assets/avatars/nid/humour/tribune/avatar-hibou-humour-tribune-megaphone.png',true),
  ('avatar-hibou-humour-tribune-porte-drapeau','Porte-drapeau','Humour · Tribune',63,'assets/avatars/nid/humour/tribune/avatar-hibou-humour-tribune-porte-drapeau.png',true),
  ('avatar-hibou-humour-tribune-doigt-mousse','Doigt en mousse','Humour · Tribune',64,'assets/avatars/nid/humour/tribune/avatar-hibou-humour-tribune-doigt-mousse.png',true),
  ('avatar-hibou-humour-tribune-jumelles','Jumelles de tribune','Humour · Tribune',65,'assets/avatars/nid/humour/tribune/avatar-hibou-humour-tribune-jumelles.png',true),
  ('avatar-hibou-humour-tribune-levitation','Supporter en lévitation','Humour · Tribune',66,'assets/avatars/nid/humour/tribune/avatar-hibou-humour-tribune-levitation.png',true),
  ('avatar-hibou-humour-tribune-ballon-porte-bonheur','Ballon porte-bonheur','Humour · Tribune',67,'assets/avatars/nid/humour/tribune/avatar-hibou-humour-tribune-ballon-porte-bonheur.png',true),
  ('avatar-hibou-humour-tribune-popcorn-3d','Pop-corn 3D','Humour · Tribune',68,'assets/avatars/nid/humour/tribune/avatar-hibou-humour-tribune-popcorn-3d.png',true),
  ('avatar-hibou-humour-tribune-perruque-kop','Perruque du kop','Humour · Tribune',69,'assets/avatars/nid/humour/tribune/avatar-hibou-humour-tribune-perruque-kop.png',true),
  ('avatar-hibou-humour-tribune-danse-victoire','Danse de victoire','Humour · Tribune',70,'assets/avatars/nid/humour/tribune/avatar-hibou-humour-tribune-danse-victoire.png',true),
  ('avatar-hibou-humour-tribune-lunettes-stade','Lunettes du stade','Humour · Tribune',71,'assets/avatars/nid/humour/tribune/avatar-hibou-humour-tribune-lunettes-stade.png',true),
  ('avatar-hibou-humour-tribune-tacle-imaginaire','Tacle imaginaire','Humour · Tribune',72,'assets/avatars/nid/humour/tribune/avatar-hibou-humour-tribune-tacle-imaginaire.png',true),
  ('avatar-hibou-humour-canape-telecommande-popcorn','Télécommande & pop-corn','Humour · Canapé',73,'assets/avatars/nid/humour/canape/avatar-hibou-humour-canape-telecommande-popcorn.png',true),
  ('avatar-hibou-humour-canape-pizza-match','Pizza du match','Humour · Canapé',74,'assets/avatars/nid/humour/canape/avatar-hibou-humour-canape-pizza-match.png',true),
  ('avatar-hibou-humour-canape-plaid-tactique','Plaid tactique','Humour · Canapé',75,'assets/avatars/nid/humour/canape/avatar-hibou-humour-canape-plaid-tactique.png',true),
  ('avatar-hibou-humour-canape-sieste-match','Sieste devant le match','Humour · Canapé',76,'assets/avatars/nid/humour/canape/avatar-hibou-humour-canape-sieste-match.png',true),
  ('avatar-hibou-humour-canape-chaussettes-chance','Chaussettes porte-bonheur','Humour · Canapé',77,'assets/avatars/nid/humour/canape/avatar-hibou-humour-canape-chaussettes-chance.png',true),
  ('avatar-hibou-humour-canape-telephone-surchauffe','Téléphone en surchauffe','Humour · Canapé',78,'assets/avatars/nid/humour/canape/avatar-hibou-humour-canape-telephone-surchauffe.png',true),
  ('avatar-hibou-humour-canape-defaite-canape','Défaite canapé','Humour · Canapé',79,'assets/avatars/nid/humour/canape/avatar-hibou-humour-canape-defaite-canape.png',true),
  ('avatar-hibou-humour-canape-cinema-foot','Cinéma du foot','Humour · Canapé',80,'assets/avatars/nid/humour/canape/avatar-hibou-humour-canape-cinema-foot.png',true),
  ('avatar-hibou-humour-canape-dodo-ballon','Dodo ballon','Humour · Canapé',81,'assets/avatars/nid/humour/canape/avatar-hibou-humour-canape-dodo-ballon.png',true),
  ('avatar-hibou-humour-canape-gamer','Gamer du Nid','Humour · Canapé',82,'assets/avatars/nid/humour/canape/avatar-hibou-humour-canape-gamer.png',true),
  ('avatar-hibou-humour-canape-match-tele','Match à la télé','Humour · Canapé',83,'assets/avatars/nid/humour/canape/avatar-hibou-humour-canape-match-tele.png',true),
  ('avatar-hibou-humour-canape-supporter-bondissant','Supporter bondissant','Humour · Canapé',84,'assets/avatars/nid/humour/canape/avatar-hibou-humour-canape-supporter-bondissant.png',true),
  ('avatar-hibou-humour-arbitrage-carton-rouge','Carton rouge','Humour · Arbitrage',85,'assets/avatars/nid/humour/arbitrage/avatar-hibou-humour-arbitrage-carton-rouge.png',true),
  ('avatar-hibou-humour-arbitrage-var-furieuse','VAR furieuse','Humour · Arbitrage',86,'assets/avatars/nid/humour/arbitrage/avatar-hibou-humour-arbitrage-var-furieuse.png',true),
  ('avatar-hibou-humour-arbitrage-facepalm-arbitral','Facepalm arbitral','Humour · Arbitrage',87,'assets/avatars/nid/humour/arbitrage/avatar-hibou-humour-arbitrage-facepalm-arbitral.png',true),
  ('avatar-hibou-humour-arbitrage-juge-touche','Juge de touche','Humour · Arbitrage',88,'assets/avatars/nid/humour/arbitrage/avatar-hibou-humour-arbitrage-juge-touche.png',true),
  ('avatar-hibou-humour-arbitrage-priere-var','Prière pour le VAR','Humour · Arbitrage',89,'assets/avatars/nid/humour/arbitrage/avatar-hibou-humour-arbitrage-priere-var.png',true),
  ('avatar-hibou-humour-arbitrage-larmes-supporter','Larmes du supporter','Humour · Arbitrage',90,'assets/avatars/nid/humour/arbitrage/avatar-hibou-humour-arbitrage-larmes-supporter.png',true),
  ('avatar-hibou-humour-arbitrage-deal-with-it','Deal with it','Humour · Arbitrage',91,'assets/avatars/nid/humour/arbitrage/avatar-hibou-humour-arbitrage-deal-with-it.png',true),
  ('avatar-hibou-humour-arbitrage-coach-complotiste','Coach complotiste','Humour · Arbitrage',92,'assets/avatars/nid/humour/arbitrage/avatar-hibou-humour-arbitrage-coach-complotiste.png',true),
  ('avatar-hibou-humour-arbitrage-mais-enfin','Mais enfin !','Humour · Arbitrage',93,'assets/avatars/nid/humour/arbitrage/avatar-hibou-humour-arbitrage-mais-enfin.png',true),
  ('avatar-hibou-humour-arbitrage-ange-innocent','Ange innocent','Humour · Arbitrage',94,'assets/avatars/nid/humour/arbitrage/avatar-hibou-humour-arbitrage-ange-innocent.png',true),
  ('avatar-hibou-humour-arbitrage-choc-score','Choc du score','Humour · Arbitrage',95,'assets/avatars/nid/humour/arbitrage/avatar-hibou-humour-arbitrage-choc-score.png',true),
  ('avatar-hibou-humour-arbitrage-hibou-furieux','Hibou furieux','Humour · Arbitrage',96,'assets/avatars/nid/humour/arbitrage/avatar-hibou-humour-arbitrage-hibou-furieux.png',true),
  ('avatar-hibou-humour-victoire-amour-coupe','Amour de la coupe','Humour · Victoire',97,'assets/avatars/nid/humour/victoire/avatar-hibou-humour-victoire-amour-coupe.png',true),
  ('avatar-hibou-humour-victoire-canon-confettis','Canon à confettis','Humour · Victoire',98,'assets/avatars/nid/humour/victoire/avatar-hibou-humour-victoire-canon-confettis.png',true),
  ('avatar-hibou-humour-victoire-roi-match','Roi du match','Humour · Victoire',99,'assets/avatars/nid/humour/victoire/avatar-hibou-humour-victoire-roi-match.png',true),
  ('avatar-hibou-humour-victoire-dj-champion','DJ champion','Humour · Victoire',100,'assets/avatars/nid/humour/victoire/avatar-hibou-humour-victoire-dj-champion.png',true),
  ('avatar-hibou-humour-victoire-selfie-victoire','Selfie victoire','Humour · Victoire',101,'assets/avatars/nid/humour/victoire/avatar-hibou-humour-victoire-selfie-victoire.png',true),
  ('avatar-hibou-humour-victoire-patron','Le patron','Humour · Victoire',102,'assets/avatars/nid/humour/victoire/avatar-hibou-humour-victoire-patron.png',true),
  ('avatar-hibou-humour-victoire-medaille-xxl','Médaille XXL','Humour · Victoire',103,'assets/avatars/nid/humour/victoire/avatar-hibou-humour-victoire-medaille-xxl.png',true),
  ('avatar-hibou-humour-victoire-bouteille-champion','Bouteille du champion','Humour · Victoire',104,'assets/avatars/nid/humour/victoire/avatar-hibou-humour-victoire-bouteille-champion.png',true),
  ('avatar-hibou-humour-victoire-feux-artifice','Feux d’artifice','Humour · Victoire',105,'assets/avatars/nid/humour/victoire/avatar-hibou-humour-victoire-feux-artifice.png',true),
  ('avatar-hibou-humour-victoire-priere-champion','Prière du champion','Humour · Victoire',106,'assets/avatars/nid/humour/victoire/avatar-hibou-humour-victoire-priere-champion.png',true),
  ('avatar-hibou-humour-victoire-sieste-coupe','Sieste avec la coupe','Humour · Victoire',107,'assets/avatars/nid/humour/victoire/avatar-hibou-humour-victoire-sieste-coupe.png',true),
  ('avatar-hibou-humour-victoire-crampons-or','Crampons d’or','Humour · Victoire',108,'assets/avatars/nid/humour/victoire/avatar-hibou-humour-victoire-crampons-or.png',true),
  ('avatar-hibou-humour-poisse-coeur-brise','Cœur brisé','Humour · Poisse',109,'assets/avatars/nid/humour/poisse/avatar-hibou-humour-poisse-coeur-brise.png',true),
  ('avatar-hibou-humour-poisse-cafe-renverse','Café renversé','Humour · Poisse',110,'assets/avatars/nid/humour/poisse/avatar-hibou-humour-poisse-cafe-renverse.png',true),
  ('avatar-hibou-humour-poisse-stress-total','Stress total','Humour · Poisse',111,'assets/avatars/nid/humour/poisse/avatar-hibou-humour-poisse-stress-total.png',true),
  ('avatar-hibou-humour-poisse-reveil-rate','Réveil raté','Humour · Poisse',112,'assets/avatars/nid/humour/poisse/avatar-hibou-humour-poisse-reveil-rate.png',true),
  ('avatar-hibou-humour-poisse-pluie-match','Pluie de match','Humour · Poisse',113,'assets/avatars/nid/humour/poisse/avatar-hibou-humour-poisse-pluie-match.png',true),
  ('avatar-hibou-humour-poisse-nuage-noir','Nuage noir','Humour · Poisse',114,'assets/avatars/nid/humour/poisse/avatar-hibou-humour-poisse-nuage-noir.png',true),
  ('avatar-hibou-humour-poisse-tete-tourne','Tête qui tourne','Humour · Poisse',115,'assets/avatars/nid/humour/poisse/avatar-hibou-humour-poisse-tete-tourne.png',true),
  ('avatar-hibou-humour-poisse-drapeau-blanc','Drapeau blanc','Humour · Poisse',116,'assets/avatars/nid/humour/poisse/avatar-hibou-humour-poisse-drapeau-blanc.png',true),
  ('avatar-hibou-humour-poisse-blesse-dimanche','Blessé du dimanche','Humour · Poisse',117,'assets/avatars/nid/humour/poisse/avatar-hibou-humour-poisse-blesse-dimanche.png',true),
  ('avatar-hibou-humour-poisse-chat-noir','Chat noir','Humour · Poisse',118,'assets/avatars/nid/humour/poisse/avatar-hibou-humour-poisse-chat-noir.png',true),
  ('avatar-hibou-humour-poisse-ko-technique','KO technique','Humour · Poisse',119,'assets/avatars/nid/humour/poisse/avatar-hibou-humour-poisse-ko-technique.png',true),
  ('avatar-hibou-humour-poisse-ballon-rafistole','Ballon rafistolé','Humour · Poisse',120,'assets/avatars/nid/humour/poisse/avatar-hibou-humour-poisse-ballon-rafistole.png',true),
  ('avatar-hibou-humour-bbq-chef-barbecue','Chef du barbecue','Humour · BBQ',121,'assets/avatars/nid/humour/bbq/avatar-hibou-humour-bbq-chef-barbecue.png',true),
  ('avatar-hibou-humour-bbq-saucisse-volante','Saucisse volante','Humour · BBQ',122,'assets/avatars/nid/humour/bbq/avatar-hibou-humour-bbq-saucisse-volante.png',true),
  ('avatar-hibou-humour-bbq-roi-camping','Roi du camping','Humour · BBQ',123,'assets/avatars/nid/humour/bbq/avatar-hibou-humour-bbq-roi-camping.png',true),
  ('avatar-hibou-humour-bbq-grillade-feu','Grillade en feu','Humour · BBQ',124,'assets/avatars/nid/humour/bbq/avatar-hibou-humour-bbq-grillade-feu.png',true),
  ('avatar-hibou-humour-bbq-pique-nique','Pique-nique du match','Humour · BBQ',125,'assets/avatars/nid/humour/bbq/avatar-hibou-humour-bbq-pique-nique.png',true),
  ('avatar-hibou-humour-bbq-hot-dog','Hot-dog du Nid','Humour · BBQ',126,'assets/avatars/nid/humour/bbq/avatar-hibou-humour-bbq-hot-dog.png',true),
  ('avatar-hibou-humour-bbq-plancha','Plancha du Nid','Humour · BBQ',127,'assets/avatars/nid/humour/bbq/avatar-hibou-humour-bbq-plancha.png',true),
  ('avatar-hibou-humour-bbq-triple-burger','Triple burger','Humour · BBQ',128,'assets/avatars/nid/humour/bbq/avatar-hibou-humour-bbq-triple-burger.png',true),
  ('avatar-hibou-humour-bbq-saucisse-biere','Saucisse & bière','Humour · BBQ',129,'assets/avatars/nid/humour/bbq/avatar-hibou-humour-bbq-saucisse-biere.png',true),
  ('avatar-hibou-humour-bbq-glaciere-kop','Glacière du kop','Humour · BBQ',130,'assets/avatars/nid/humour/bbq/avatar-hibou-humour-bbq-glaciere-kop.png',true),
  ('avatar-hibou-humour-bbq-barbecue-ballon','Barbecue ballon','Humour · BBQ',131,'assets/avatars/nid/humour/bbq/avatar-hibou-humour-bbq-barbecue-ballon.png',true),
  ('avatar-hibou-humour-bbq-hot-dog-heureux','Hot-dog heureux','Humour · BBQ',132,'assets/avatars/nid/humour/bbq/avatar-hibou-humour-bbq-hot-dog-heureux.png',true),
  ('avatar-hibou-humour-deguisements-gentleman','Gentleman moustachu','Humour · Déguisements',133,'assets/avatars/nid/humour/deguisements/avatar-hibou-humour-deguisements-gentleman.png',true),
  ('avatar-hibou-humour-deguisements-star-kop','Star du kop','Humour · Déguisements',134,'assets/avatars/nid/humour/deguisements/avatar-hibou-humour-deguisements-star-kop.png',true),
  ('avatar-hibou-humour-deguisements-super-hibou','Super Hibou','Humour · Déguisements',135,'assets/avatars/nid/humour/deguisements/avatar-hibou-humour-deguisements-super-hibou.png',true),
  ('avatar-hibou-humour-deguisements-bouffon','Bouffon du Nid','Humour · Déguisements',136,'assets/avatars/nid/humour/deguisements/avatar-hibou-humour-deguisements-bouffon.png',true),
  ('avatar-hibou-humour-deguisements-annees-80','Années 80','Humour · Déguisements',137,'assets/avatars/nid/humour/deguisements/avatar-hibou-humour-deguisements-annees-80.png',true),
  ('avatar-hibou-humour-deguisements-pirate','Pirate du Nid','Humour · Déguisements',138,'assets/avatars/nid/humour/deguisements/avatar-hibou-humour-deguisements-pirate.png',true),
  ('avatar-hibou-humour-deguisements-chevalier','Chevalier du Nid','Humour · Déguisements',139,'assets/avatars/nid/humour/deguisements/avatar-hibou-humour-deguisements-chevalier.png',true),
  ('avatar-hibou-humour-deguisements-disco','Disco Hibou','Humour · Déguisements',140,'assets/avatars/nid/humour/deguisements/avatar-hibou-humour-deguisements-disco.png',true),
  ('avatar-hibou-humour-deguisements-magicien','Magicien','Humour · Déguisements',141,'assets/avatars/nid/humour/deguisements/avatar-hibou-humour-deguisements-magicien.png',true),
  ('avatar-hibou-humour-deguisements-roi','Roi du Nid','Humour · Déguisements',142,'assets/avatars/nid/humour/deguisements/avatar-hibou-humour-deguisements-roi.png',true),
  ('avatar-hibou-humour-deguisements-vacancier','Vacancier','Humour · Déguisements',143,'assets/avatars/nid/humour/deguisements/avatar-hibou-humour-deguisements-vacancier.png',true),
  ('avatar-hibou-humour-deguisements-viking','Viking du Nid','Humour · Déguisements',144,'assets/avatars/nid/humour/deguisements/avatar-hibou-humour-deguisements-viking.png',true),
  ('avatar-hibou-humour-cafe-pmu-petit-cafe','Petit café','Humour · Café & PMU',145,'assets/avatars/nid/humour/cafe-pmu/avatar-hibou-humour-cafe-pmu-petit-cafe.png',true),
  ('avatar-hibou-humour-cafe-pmu-journal-courses','Journal des courses','Humour · Café & PMU',146,'assets/avatars/nid/humour/cafe-pmu/avatar-hibou-humour-cafe-pmu-journal-courses.png',true),
  ('avatar-hibou-humour-cafe-pmu-parieur-stylo','Parieur au stylo','Humour · Café & PMU',147,'assets/avatars/nid/humour/cafe-pmu/avatar-hibou-humour-cafe-pmu-parieur-stylo.png',true),
  ('avatar-hibou-humour-cafe-pmu-croissant-cafe','Croissant café','Humour · Café & PMU',148,'assets/avatars/nid/humour/cafe-pmu/avatar-hibou-humour-cafe-pmu-croissant-cafe.png',true),
  ('avatar-hibou-humour-cafe-pmu-apero-terrasse','Apéro terrasse','Humour · Café & PMU',149,'assets/avatars/nid/humour/cafe-pmu/avatar-hibou-humour-cafe-pmu-apero-terrasse.png',true),
  ('avatar-hibou-humour-cafe-pmu-poker','Poker du Nid','Humour · Café & PMU',150,'assets/avatars/nid/humour/cafe-pmu/avatar-hibou-humour-cafe-pmu-poker.png',true),
  ('avatar-hibou-humour-cafe-pmu-biere-comptoir','Bière au comptoir','Humour · Café & PMU',151,'assets/avatars/nid/humour/cafe-pmu/avatar-hibou-humour-cafe-pmu-biere-comptoir.png',true),
  ('avatar-hibou-humour-cafe-pmu-pronostics-hippiques','Pronostics hippiques','Humour · Café & PMU',152,'assets/avatars/nid/humour/cafe-pmu/avatar-hibou-humour-cafe-pmu-pronostics-hippiques.png',true),
  ('avatar-hibou-humour-cafe-pmu-cafe-serre','Café serré','Humour · Café & PMU',153,'assets/avatars/nid/humour/cafe-pmu/avatar-hibou-humour-cafe-pmu-cafe-serre.png',true),
  ('avatar-hibou-humour-cafe-pmu-porte-bonheur','Porte-bonheur','Humour · Café & PMU',154,'assets/avatars/nid/humour/cafe-pmu/avatar-hibou-humour-cafe-pmu-porte-bonheur.png',true),
  ('avatar-hibou-humour-cafe-pmu-rendez-vous','Rendez-vous galant','Humour · Café & PMU',155,'assets/avatars/nid/humour/cafe-pmu/avatar-hibou-humour-cafe-pmu-rendez-vous.png',true),
  ('avatar-hibou-humour-cafe-pmu-trompette-bistrot','Trompette du bistrot','Humour · Café & PMU',156,'assets/avatars/nid/humour/cafe-pmu/avatar-hibou-humour-cafe-pmu-trompette-bistrot.png',true),
  ('avatar-hibou-humour-personnages-chanceux','Le chanceux','Humour · Personnages',157,'assets/avatars/nid/humour/personnages/avatar-hibou-humour-personnages-chanceux.png',true),
  ('avatar-hibou-humour-personnages-analyste','L’analyste','Humour · Personnages',158,'assets/avatars/nid/humour/personnages/avatar-hibou-humour-personnages-analyste.png',true),
  ('avatar-hibou-humour-personnages-arbitre-strict','L’arbitre strict','Humour · Personnages',159,'assets/avatars/nid/humour/personnages/avatar-hibou-humour-personnages-arbitre-strict.png',true),
  ('avatar-hibou-humour-personnages-selfie-supporter','Le selfie supporter','Humour · Personnages',160,'assets/avatars/nid/humour/personnages/avatar-hibou-humour-personnages-selfie-supporter.png',true),
  ('avatar-hibou-humour-personnages-popcorn-geant','Pop-corn géant','Humour · Personnages',161,'assets/avatars/nid/humour/personnages/avatar-hibou-humour-personnages-popcorn-geant.png',true),
  ('avatar-hibou-humour-personnages-zen','Le zen','Humour · Personnages',162,'assets/avatars/nid/humour/personnages/avatar-hibou-humour-personnages-zen.png',true),
  ('avatar-hibou-humour-personnages-oracle-meteo','Oracle météo','Humour · Personnages',163,'assets/avatars/nid/humour/personnages/avatar-hibou-humour-personnages-oracle-meteo.png',true),
  ('avatar-hibou-humour-personnages-genie','Le génie','Humour · Personnages',164,'assets/avatars/nid/humour/personnages/avatar-hibou-humour-personnages-genie.png',true),
  ('avatar-hibou-humour-personnages-commentateur','Le commentateur','Humour · Personnages',165,'assets/avatars/nid/humour/personnages/avatar-hibou-humour-personnages-commentateur.png',true),
  ('avatar-hibou-humour-personnages-echarpes-empilees','Écharpes empilées','Humour · Personnages',166,'assets/avatars/nid/humour/personnages/avatar-hibou-humour-personnages-echarpes-empilees.png',true),
  ('avatar-hibou-humour-personnages-globe-trotter','Globe-trotter','Humour · Personnages',167,'assets/avatars/nid/humour/personnages/avatar-hibou-humour-personnages-globe-trotter.png',true),
  ('avatar-hibou-humour-personnages-cotillons','Cotillons','Humour · Personnages',168,'assets/avatars/nid/humour/personnages/avatar-hibou-humour-personnages-cotillons.png',true)
on conflict(avatar_key) do update
set label=excluded.label,
    category=excluded.category,
    sort_order=excluded.sort_order,
    asset_path=excluded.asset_path,
    active=excluded.active;

commit;

-- Contrôle attendu : 168 lignes actives.
select count(*) as avatars_actifs
from public.player_avatar_catalog
where active = true;
